### ISSUE TITLE
Create sample document and review it

### ISSUE THREAD

**Issue by petrkotas** [DataAnalysisMentoring/git_tutorial#2]
1) @Radulka udělá novou větev, jedno jak se jmenuje
2) @Radulka vytvoří v té větvi jednoduchý textový dokument, třeba [lipsum](https://www.lipsum.com/), ten
3) @Radulka do větve uloží změny a "pushne" je sem na github, s tím, že vytvoří novou větev `git push -u vetev`
4) @Radulka vytvoří pull request a přidá @hahahanni na review
5) @hahahanni jí udělá review, a mergne to
6) celé se to otočí :)

**Comment by Radulka** [comment]
sice jsem ukol splnila, ale porad spravne nechapu, jak :)
